"""added about_me_html to users table

Revision ID: 0b2d52dea494
Revises: 3413a4c31b5d
Create Date: 2021-09-06 19:25:55.383687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2d52dea494'
down_revision = '3413a4c31b5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_me_html')
    # ### end Alembic commands ###
