"""added disabled column to comment

Revision ID: 3bf8948188b1
Revises: d6d904867483
Create Date: 2021-09-18 17:08:44.915030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf8948188b1'
down_revision = 'd6d904867483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'disabled')
    # ### end Alembic commands ###
